#!/bin/ksh
#         __         _______    __
#        / /  ___   /__  __/ __/ /  ____
#       / /  / _ |_   / / / / / /  / __/     auto
#      / /__/ __ | \_/ / /_/ / /__/ -__      2012, Julien Rouzieres
#     /____/_/ |_|\___/|____/____/____/      https://github.com/Lajule/auto
#

# Normal termination.
function bye {
  let success=0

  print - "${0##*/}: $*"
  exit $success
}
