#!/bin/ksh
#         __         _______    __
#        / /  ___   /__  __/ __/ /  ____
#       / /  / _ |_   / / / / / /  / __/     auto
#      / /__/ __ | \_/ / /_/ / /__/ -__      2012, Julien Rouzieres
#     /____/_/ |_|\___/|____/____/____/      https://github.com/Lajule/auto
#

# Capitalizes the given string.
function capitalize {
  typeset -r str=$*
  typeset -ru cap=${str%${str#[a-z]}}

  print - "$cap${str#[a-z]}"
}
