#!/bin/ksh
#         __            __      __
#        / /  ___      / /_  __/ /  ____
#       / /  / _ |_   / / / / / /  / __/     auto
#      / /__/ __ | \_/ / /_/ / /__/ -__      2012, Julien Rouzieres
#     /____/_/ |_|\___/|____/____/____/      https://github.com/Lajule/auto
#

# Anormal termination.
function die {
  let failure=1

  print -u2 - "${0##*/}: $*"
  exit $failure
}
