#!/bin/ksh
#         __          _______    __
#        / /  ___    /__  __/ __/ /  ____
#       / /  / _ | __  / / / / / /  / __/        auto
#      / /__/ __ |/ /_/ / /_/ / /__/ -__         2012, Julien Rouzieres
#     /____/_/ |_|\____/|____/____/____/         https://github.com/Lajule/auto
#

# Anormal termination.
function die {
  let failure=1

  print -u2 - "${0##*/}: $*"
  exit $failure
}
