#!/bin/ksh
#         __          _______    __
#        / /  ___    /__  __/ __/ /  ____
#       / /  / _ | __  / / / / / /  / __/        auto
#      / /__/ __ |/ /_/ / /_/ / /__/ -__         2012, Julien Rouzieres
#     /____/_/ |_|\____/|____/____/____/         https://github.com/Lajule/auto
#

# Converts a dos file to a unix one.
function dos2unix {
  typeset -r tmp=/tmp/dos2unix.$$

  for f in $@; do
    if [[ -f $f ]]; then
      tr -d '\r' <$f >$tmp
      mv $tmp $f
    fi
  done
}
