#!/bin/ksh

# Converts a dos file to a unix one.
function dos2unix {
  typeset -r tmp=/tmp/dos2unix.$$

  for f in "$@"; do
    if [[ -f $f ]]; then
      tr -d '\r' <$f >$tmp
      mv $tmp $f
    fi
  done
}
