#!/bin/ksh
#         __          _______    __
#        / /  ___    /__  __/ __/ /  ____
#       / /  / _ | __  / / / / / /  / __/        auto
#      / /__/ __ |/ /_/ / /_/ / /__/ -__         2012, Julien Rouzieres
#     /____/_/ |_|\____/|____/____/____/         https://github.com/Lajule/auto
#

# Prints the position (form the beginning) of given character in given string.
function index {
  let index=-1

  typeset -r str=${1%%$2*}
  if [[ $1 != $str ]]; then
    let index=${#str}
  fi

  print - $index
}
