#!/bin/ksh
#         __            __      __
#        / /  ___      / /_  __/ /  ____
#       / /  / _ |_   / / / / / /  / __/     auto
#      / /__/ __ | \_/ / /_/ / /__/ -__      2012, Julien Rouzieres
#     /____/_/ |_|\___/|____/____/____/      https://github.com/Lajule/auto
#

# The default lock file name is built here.
typeset -r LOCKFILE="$0.lock"

# Returns 1 if a previous instance is running, otherwise returns 0.
function lock {
  typeset -r tempfile="$LOCKFILE.$$"

  if ! print $$ >$tempfile; then
    return 1
  fi

  if ln -n $tempfile $LOCKFILE 2>/dev/null; then
    rm -f $tempfile
    return 0
  fi

  if kill -0 $(cat $LOCKFILE); then
    rm -f $tempfile
    return 1
  fi

  rm -f $LOCKFILE
  if ln -n $tempfile $LOCKFILE 2>/dev/null; then
    rm -f $tempfile
    return 0
  fi

  rm -f $tempfile
  return 1
}

# Releases lock for others instances.
function unlock {
  rm -f $LOCKFILE
}
