#!/bin/ksh

# Define the program name.
typeset progname=$0.lock

# Returns 1 if a previous instance is running, otherwise returns 0.
function lock {
  typeset -r tempfile="$LOCKFILE.$$"

  if ! print $$ >$tempfile; then
    return 1
  fi

  if ln -n $tempfile $LOCKFILE 2>/dev/null; then
    rm -f $tempfile
    return 0
  fi

  if kill -0 $(cat $LOCKFILE); then
    rm -f $tempfile
    return 1
  fi

  rm -f $LOCKFILE
  if ln -n $tempfile $LOCKFILE 2>/dev/null; then
    rm -f $tempfile
    return 0
  fi

  rm -f $tempfile
  return 1
}

# Releases lock for others instances.
function unlock {
  rm -f $LOCKFILE
}
