#!/bin/ksh

# Define the calling script name.
typeset scriptname=${0##*/}

# Returns a new temporary file name.
function mktmpf {
  typeset -r d=${TMPDIR:-/tmp}
  typeset -r f=$scriptname.$$

  let n=$(find $d -type f -name "$f.*" | wc -l | tr -d '[:blank:]')+1
  print "$d/$f.$n"
}
