#!/bin/ksh
#         __         _______    __
#        / /  ___   /__  __/ __/ /  ____
#       / /  / _ |_   / / / / / /  / __/     auto
#      / /__/ __ | \_/ / /_/ / /__/ -__      2012, Julien Rouzieres
#     /____/_/ |_|\___/|____/____/____/      https://github.com/Lajule/auto
#

# Returns a new temporary file name.
function mktmpf {
  typeset -r d=${TMPDIR:-/tmp}
  typeset -r f=${0##*/}.$$

  let n=$(find $d -type f -name "$f.*" | wc -l | tr -d '[:blank:]')+1
  print "$d/$f.$n"
}
