#!/bin/ksh

# Define the program name.
typeset progname=${0##*/}

# Returns a new temporary file name.
function mktmpf {
  typeset -r d=${TMPDIR:-/tmp}
  typeset -r f=$progname.$$

  let n=$(find $d -type f -name "$f.*" | wc -l | tr -d '[:blank:]')+1
  print "$d/$f.$n"
}
