#!/bin/ksh
#         __         _______    __
#        / /  ___   /__  __/ __/ /  ____
#       / /  / _ |_   / / / / / /  / __/     auto
#      / /__/ __ | \_/ / /_/ / /__/ -__      2012, Julien Rouzieres
#     /____/_/ |_|\___/|____/____/____/      https://github.com/Lajule/auto
#

# Right pads the given string with given character.
function pad {
  typeset str=$1

  while (( ${#str} < ${2:-0} )); do
    str="${3:- }$str"
  done

  print - "$str"
}
