#!/bin/ksh
#         __         _______    __
#        / /  ___   /__  __/ __/ /  ____
#       / /  / _ |_   / / / / / /  / __/     auto
#      / /__/ __ | \_/ / /_/ / /__/ -__      2012, Julien Rouzieres
#     /____/_/ |_|\___/|____/____/____/      https://github.com/Lajule/auto
#

# Sets a pretty prompt.
function prompt {
  typeset -r mode=${1:-simple}
  case $mode in
    tiny)
      export PS1="$ ";;

    simple)
      export PS1="$LOGNAME@$(hostname) $ ";;

    full)
      set -A dirs $(print $PWD | sed 's/\// /g')
      if ((${#dirs[*]} > 5)); then
        typeset pwd=".."
        for i in 5 4 3 2 1; do
          typeset pwd="$pwd/${dirs[$((${#dirs[*]} - $i))]}"
        done
      fi

      export PS1="
$LOGNAME@$(hostname):${pwd:-$PWD}
! $(date +%H:%M:%S) $ ";;
  esac
}
