#!/bin/ksh

# Quotes the given string.
function quote {
  typeset -r type=$1

  shift
  case $type in
    gnu)
      print - "\`$*'";;
    single)
      print - "'$*'";;
    double)
      print - "\"$*\"";;
    back)
      print - "\`$*\`";;
    *)
      print - "\`$type'";;
  esac
}
