#!/bin/ksh
#         __         _______    __
#        / /  ___   /__  __/ __/ /  ____
#       / /  / _ |_   / / / / / /  / __/     auto
#      / /__/ __ | \_/ / /_/ / /__/ -__      2012, Julien Rouzieres
#     /____/_/ |_|\___/|____/____/____/      https://github.com/Lajule/auto
#

# Reads a line and stores the result in given variable name.
function readline {
  if [[ -t 0 ]]; then
    if [[ -z $stty ]]; then
      stty=$(stty -g)
    fi

    if [[ $1 = password ]]; then
      stty -echo
    fi
  fi

  read ${1:-line}

  if [[ -t 0 ]]; then
    stty $stty
  fi
}
