#!/bin/ksh
#         __            __      __
#        / /  ___      / /_  __/ /  ____
#       / /  / _ |_   / / / / / /  / __/     auto
#      / /__/ __ | \_/ / /_/ / /__/ -__      2012, Julien Rouzieres
#     /____/_/ |_|\___/|____/____/____/      https://github.com/Lajule/auto
#

# Reads a key and stores the result in given variable name.
function readkey {
  if [[ -t 0 ]]; then
    if [[ -z $stty ]]; then
      stty=$(stty -g)
    fi

    stty -echo -icanon min 1
  fi

  eval ${1:-key}=$(dd bs=1 count=1 2>/dev/null)

  if [[ -t 0 ]]; then
    stty $stty
  fi
}
