#!/bin/ksh

# Prints the position (form the end) of given character in given string.
function rindex {
  let rindex=-1

  typeset -r str=${1##*$2}
  if [[ $1 != $str ]]; then
    let rindex=${#str}
  fi

  print - $rindex
}
