#!/bin/ksh
#         __          _______    __
#        / /  ___    /__  __/ __/ /  ____
#       / /  / _ | __  / / / / / /  / __/        auto
#      / /__/ __ |/ /_/ / /_/ / /__/ -__         2012, Julien Rouzieres
#     /____/_/ |_|\____/|____/____/____/         https://github.com/Lajule/auto
#

# Left pads the given string with given character.
function rpad {
  typeset str=$1

  while (( ${#str} < ${2:-0} )); do
    str="$str${3:- }"
  done

  print - "$str"
}
