#!/bin/ksh
#         __          _______    __
#        / /  ___    /__  __/ __/ /  ____
#       / /  / _ | __  / / / / / /  / __/        auto
#      / /__/ __ |/ /_/ / /_/ / /__/ -__         2012, Julien Rouzieres
#     /____/_/ |_|\____/|____/____/____/         https://github.com/Lajule/auto
#

# Replaces the last occurence of given pattern.
function rsub {
  case $1 in
    *$2*)
      print - "${1%$2*}$3${1##*$2}";;
    *)
      print - "$1";;
  esac
}
