#!/bin/ksh

# Converts a unix file to a DOS one.
function unix2dos {
  typeset -r tmp=/tmp/unix2dos.$$

  for f in $@; do
    if [[ -f $f ]]; then
      sed 's/$/\r/g' $f >$tmp
      mv $tmp $f
    fi
  done
}
