#!/bin/ksh
#         __            __      __
#        / /  ___      / /_  __/ /  ____
#       / /  / _ |_   / / / / / /  / __/     auto
#      / /__/ __ | \_/ / /_/ / /__/ -__      2012, Julien Rouzieres
#     /____/_/ |_|\___/|____/____/____/      https://github.com/Lajule/auto
#

# Converts a unix file to a DOS one.
function unix2dos {
  typeset -r tmp=/tmp/unix2dos.$$

  for f in $@; do
    if [[ -f $f ]]; then
      sed 's/$/\r/g' $f >$tmp
      mv $tmp $f
    fi
  done
}
