#!/bin/ksh
#         __         _______    __
#        / /  ___   /__  __/ __/ /  ____
#       / /  / _ |_   / / / / / /  / __/     auto
#      / /__/ __ | \_/ / /_/ / /__/ -__      2012, Julien Rouzieres
#     /____/_/ |_|\___/|____/____/____/      https://github.com/Lajule/auto
#

# Converts tabs into spaces.
function untabify {
  typeset tab="  "

  while getopts "24" opt; do
    case $opt in
      2)
        typeset -rL2 tab;;

      4)
        typeset -rL4 tab;;
    esac
  done
  shift $(($OPTIND - 1))

  typeset -r tmp=/tmp/untabify.$$
  for f in $@; do
    if [[ -f $f ]]; then
      sed "s/	/$tab/g" $f >$tmp
      mv $tmp $f
    fi
  done
}
